[build]
builder = "DOCKERFILE"
watchPatterns = ["/be/**"]
dockerfilePath = "/be/dockerfile.prod"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true
useLegacyStacker = false
multiRegionConfig = {"asia-southeast1-eqsg3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10